---
language: python
services:
  - docker
install:
  - pip install -r requirements.txt
  - curl -s https://raw.githubusercontent.com/aws-quickstart/taskcat/master/installer/docker-installer.sh
script:
  - taskcat -c ci/taskcat.yml

notifications:
  slack:
    secure: z+Y78wFtnLir0NEJOlQ9Ry+IXnsf9TpMXRgAhJVYTAlD0hLhYycPpcptObd7SkWBp0Fh9FdsuNJArAt+H+Bs3YGkCO70ZhjKdIfTXdOp8bk2lO0Szf0H8gKhT+9hw2gV1IxdhOCsztuSeVyLfMyAKhKRwfm+vE9bYdeENHsDOXyzFji1TAELxlODWGj5SWcEU0qB2IPJw2Jc9631QnzSKa86XM5Ov90vG01bF2ILq2RAIADphH+oVthKJubK+JKaURtnNBff94uV3hG2w+cF99Me1Lseg2MH45UAt1Y47PKgodXAJ/rBhmjGyWKrmm3rBtvSXx5IQY5ka3VgkSCjxT8n9CnNOdSDV/w6U/UlazNeMDmWzluWwFcgV3oErS9NG2GpMKEmH6FvILHRIIn+KrRAeKwSEIrmiEYAj3uf+8AjJvVEqHUB13mh1HICP/pPsaJpzk+eBa1sNJsj/iarspUOhO/Yso/QynckGp27Pyi8NVgQYjQdJLs9n4eoSPFpx/wVlUVOu9aVPwENUOquQBSZ4lBBLagEibnOrepLEV7kI3ttO3ch4BTAVRiSyYUzM7uIkFxm3GEGqvfVHbia2+5RkrozdD/m12ir2qDbqXprwQIgBfZ83KKOoMjIf9dTsd6g1IKSspN/5rem2UrL5p4InK3O0fHcqHZLkPg6zCM=
