language: python
services:
- docker
install:
- pip install -r requirements.txt
- curl -s https://raw.githubusercontent.com/aws-quickstart/taskcat/master/installer/docker-installer.sh
script:
- taskcat -c ci/taskcat.yml

after_script:
- python clear_up_fail_stacks.py

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true

notifications:
  slack:
    secure: Ed+sjgo+rdLfzrzbFZg14PaLEFJdLRNEnnPeM/NLp5Ak8i1jxRstmvKjLmSgYK9R6jV7SeTumsQhqWMmFwWjxMkajw522bQ/JiR4D/9tvQlyDCdgHBX+tPb74OYy0vIG5unPBHd3yd7g718FJ9/9rsrhfIoCxBGvZTQsX/HKkVudipqFrB+ey+wsHyNP99Q1pYlln4OKmX2et5qRWFkVOhiKvxfto/ssVp1W2WsHdnHDw/2wBmete/5UH1Q8oGI2Ow6DdECEvPyWZmKwIml2mgoKATaqIbdKjWgAOOMy0q0sLLXf3XdijoJsayo3NBb/HdEA8VTh6i2h4/oXO6JL+4MZr2Jj0cZ7yw9BmJV6batIogLJ54x8HhEIIag/wU3otjcwczUQY7ReqBC7to4GGrFEwLSiV9g9NYP7mqkLlV44GiRinfTYqb3H+wABC52UF1DrQg/tdtnDtAqY7z6TneLWFFBiN+2yfEjHIj9FlT6i5QrU/zjRU9ea/2mvRcE+zHutIZfYRLM/ZaiewsKMRwegqoMsDeKNduDWhOn8wb+rW00KtaO/z/DBIIxphMLyVret8F9O1h2KoL6a7ixH9ZAbYHzlW5Bq/vaStUx5TiPjBdF1otgn1Mp5ZfZAgeUDGrZ/WHHli3zoKHBMqom3elzA9s6XK6uZLcf0rHgiaDg=
